export const HTTP_API_ERROR_CODE = {
    VALIDATION_FAILED: "VALIDATION_FAILED",
    DEVICE_ALREADY_ADDED: "DEVICE_ALREADY_ADDED",
    DUPLICATE_DEVICE_NAME: "DUPLICATE_DEVICE_NAME",
    INVALID_ACTION: "INVALID_ACTION",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
